ALTER TABLE "Order"
ADD COLUMN "productName" TEXT NOT NULL DEFAULT '活動商品',
ADD COLUMN "unitPrice" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "quantity" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "Order"
ALTER COLUMN "productName" DROP DEFAULT,
ALTER COLUMN "unitPrice" DROP DEFAULT,
ALTER COLUMN "quantity" DROP DEFAULT;